# Generated by Django 5.1.3 on 2024-11-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetail',
            old_name='student_id',
            new_name='student',
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
